from app import app, db
from models import MLModel

def seed_ml_models():
    # Updated models with the latest information
    model1 = MLModel(
        model_name='custom_cnn_model',
        display_name='Custom CNN Model',
        accuracy=77.0,
        description='Detects deepfakes using a custom Convolutional Neural Network (CNN) trained for image analysis.'
    )
    
    model2 = MLModel(
        model_name='mesonet_deepfake_model',
        display_name='MesoNet Deepfake Model',
        accuracy=84.5,
        description='Detects deepfakes using MesoNet architecture optimized for deepfake detection tasks.'
    )
    
    model3 = MLModel(
        model_name='mesonet_gan_model',
        display_name='MesoNet GAN Model',
        accuracy=86.8,
        description='Specialized in detecting deepfakes generated by GANs using MesoNet-based architecture.'
    )

    # Add to the session
    db.session.add(model1)
    db.session.add(model2)
    db.session.add(model3)

    # Commit the session
    db.session.commit()
    print("Updated ML Models seeded successfully!")

# Run the seeding function inside an app context
if __name__ == '__main__':
    with app.app_context():
        seed_ml_models()
